# Generated by Django 2.2 on 2019-05-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190518_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='URLmore',
            field=models.URLField(blank=True, null=True),
        ),
    ]
